version: "3.1"

services:
  paastis-registry:
    container_name: "paastis-registry"
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data

  paastis-engine:
    container_name: "paastis-engine"
    build: .
    environment:
      PROVIDER_SCALINGO_API_TOKEN: "change_me" # tk-us-xxx
      ROUTING_SYSTEM_API_ENABLED: "true"
      ROUTING_SYSTEM_API_TOKEN: "abcd-1234-EFGH-5678"
    ports:
      - "3000:3000"

volumes:
  cache:
